export const SCENARIOS = [
  {
    id: 's1',
    name: '$MOONCAT',
    emoji: '🐱',
    difficulty: 'Beginner',
    difficultyColor: 'bg-primary/10 text-primary',
    description: 'A new Solana cat-themed memecoin launched 2 hours ago. The Telegram group has 4,000 members and a pinned video of the dev.',
    fakeCA: 'MoOnCaT7xK2pQrLwY3vNfBsHdJcPtAeGiUoZmXnRvQk',
    signals: [
      'LP locked for 30 days via Unicrypt',
      'Top holder (dev wallet) owns 42% of supply',
      'Mint authority still enabled',
      'Liquidity: $18,000',
      'No contract audit',
      '24h volume: $85,000 — suspicious wash-trade pattern',
    ],
  },
  {
    id: 's2',
    name: '$AIPEPE',
    emoji: '🤖',
    difficulty: 'Intermediate',
    difficultyColor: 'bg-yellow-400/10 text-yellow-400',
    description: 'An "AI-powered" Pepe derivative on Ethereum/Base. Team is doxxed on their website with LinkedIn profiles. 3 weeks old.',
    fakeCA: '0xA1B2c3D4e5F6a7B8C9d0E1f2A3b4C5d6E7f8A9b0',
    signals: [
      'LP locked for 6 months',
      'Mint authority renounced',
      'Top 10 holders own 28% combined',
      'Liquidity: $120,000',
      'Contract audited by SolidProof',
      'Dev wallet sold 5% of holdings yesterday',
      '18 sniper wallets in first block — all still holding',
    ],
  },
  {
    id: 's3',
    name: '$SOLBULL',
    emoji: '🐂',
    difficulty: 'Beginner',
    difficultyColor: 'bg-primary/10 text-primary',
    description: 'A bull-run themed Solana token. Just launched. The team is anonymous with only a Twitter account (500 followers).',
    fakeCA: 'SoLBuLLx9QwErTyUiOpAsdfGhJkLzXcVbNm1234567',
    signals: [
      'LP not locked — dev controls pool',
      'No freeze or mint authority (Solana token)',
      'Top holder owns 65% of supply',
      'Liquidity: $6,000',
      'Launched 45 minutes ago',
      'Contract copied from known honeypot template',
    ],
  },
  {
    id: 's4',
    name: '$DAOCAT',
    emoji: '🏛️',
    difficulty: 'Advanced',
    difficultyColor: 'bg-orange-400/10 text-orange-400',
    description: 'A "community-governed" DAO cat token on Base. Has a working governance portal. 6 weeks old with growing TVL.',
    fakeCA: '0xDeAdBeEf1234567890aBcDeF1234567890aBcDeF',
    signals: [
      'LP locked for 12 months',
      'Ownership renounced after audit',
      'Top 10 wallets hold 31% — fairly distributed',
      'Liquidity: $340,000',
      'Audit by CertiK — medium severity issue unresolved',
      'Dev wallet slowly selling ~0.8% per day for 10 days',
      'Volume growing organically over 2 weeks',
      'Governance portal is a copy-paste template with no real votes',
    ],
  },
  {
    id: 's5',
    name: '$VIRALDOG',
    emoji: '🐕',
    difficulty: 'Advanced',
    difficultyColor: 'bg-orange-400/10 text-orange-400',
    description: 'Riding a viral dog meme from TikTok. Token launched 6 hours after the meme went viral. Anonymous dev, fast momentum.',
    fakeCA: 'ViRaLdOg5KmNpBqWxYzAsJhFgTrEwUiOlCvXdSa8901',
    signals: [
      'LP locked for 7 days only',
      'Mint authority disabled',
      'Top 5 wallets hold 52% — moderate concentration',
      'Liquidity: $55,000 and climbing fast',
      '3 known sniper bots in first block — 2 already sold',
      '24h volume: $1.2M — organic-looking buy pressure',
      'No audit, contract is clean (verified source code)',
      'Twitter engagement appears real, not bot-inflated',
    ],
  },
];